### PR TITLE
GitHub actions deploy pages

### LINKED ISSUE #21: Deploy to GitHub Pages
Until this is properly integrated into the nushell website, we should deploy it on GitHub Pages, to have a public preview.

Probably use GitHub Actions to build from ~mast~main.

### PR DESCRIPTION
**Pull request by jzaefferer**
TODOs:
* [ ] enable pages deploy for the gh-pages branch
* [ ] restrict this to the `main` branch

Fixes #21

### CODE REVIEW

**Comment by jzaefferer** [comment]
So far, so good: https://github.com/nushell/wasm-nu/tree/gh-pages

@jonathandturner could you enable the Pages feature for the `gh-pages` branch? 

Once that is done it works as expected, I'll update this PR to restrict the deploy to the main branch.

**Comment by jzaefferer** [comment]
Btw. 7m 23s to compile wasm-nu in the GitHub Actions runner. I assume that's going to run from scratch for every push to `main`, since those runners don't share anything. I wonder if there's some way to reuse the compiled dependencies that mostly don't change.

I found https://github.com/actions/cache/blob/master/examples.md#rust---cargo - not sure what exactly that caches.

**Comment by jonathandturner** [comment]
@jzaefferer - okay, the gh-pages branch is being selected for this repo.

**Comment by jonathandturner** [comment]
(and yeah, we should definitely figure out how to improve the build times. I'd like that for main Nu also)

**Pull request merged**
